Fix email hashing
On Python 3 the `_get_subscriber_hash` method used to fail with
following error:

    TypeError: Unicode-objects must be encoded before hashing

This happened because `email` is text string (unicode), but hashlib
expects bytes.

Fix this by encoding the email before calculating the MD5 hash.

Refs SHOOP-2540